GET http://localhost:3003/api/users
###
DELETE http://localhost:3003/api/users/
###
POST http://localhost:3003/api/users HTTP/1.1
content-type: application/json

{
    "username": "encima",
    "name": "Lucas Rodriguez",
    "password": "12"
}
###
PUT http://localhost:3003/api/users/ HTTP/1.1
content-type: application/json

{
    "author": "perito",
    "url": "jpacuco.coard.com"
}